config/routes.rb
Rails.application.routes.draw do
  resources :question_sets do
    resources :questions do
      resources :wrong_answers
    end
  end
  resources :concepts do
    resources :messages
  end
  resources :tag2wronganswers do
    resources :hints
  end
  devise_for :users
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  root to: 'pages#index'
  
  match '/forgot_password', to: 'users#forgot_password', as: "forgot_password", via: :post
  
  match '/display_users', to: 'users#index', via: :get
  match '/display_users', to: 'users#create', via: :post
  match '/display_users', to: 'users#destroy', via: :delete
  match '/display_users/:id', to: 'users#edit', via: :put
  
  match '/upload', to: 'uploads#index', via: :get
  match '/upload', to: 'uploads#new', via: :post
  match '/upload/concepts/confirmation', to: 'upload_concepts#show', via: :get
  match '/upload/concepts/confirmation', to: 'upload_concepts#confirm', via: :put
  match '/upload/tags/confirmation', to: 'upload_tags#show', via: :get
  match '/upload/tags/confirmation', to: 'upload_tags#confirm', via: :put
  match '/upload/tag2concepts/confirmation', to: 'upload_tag2concepts#show', via: :get
  match '/upload/tag2concepts/confirmation', to: 'upload_tag2concepts#confirm', via: :put
  
  match 'upload/questionsets/confirmation', to: 'upload_question_sets#show', via: :get
  match 'upload/questionsets/confirmation', to: 'upload_question_sets#confirm', via: :put
  
  match '/concepts/:concept_id/messages/:id/upvote', to: 'messages#upvote', as: "upvote", via: :post
  match '/concepts/:concept_id/messages/:id/downvote', to: 'messages#downvote', as: "downvote", via: :post
  match '/messages/threshold', to: 'messages#edit_threshold', as: "edit_threshold", via: :post
  match '/concepts/:concept_id/messages/:id/finalize', to: 'messages#finalize', as: 'finalize', via: :post
  match '/concepts/:concept_id/messages/:id/unfinalize', to: 'messages#unfinalize', as: 'unfinalize', via: :post
  
  match '/tag2wronganswers/:tag2wronganswer_id/hints/:id/upvote', to: 'hints#upvote', as: 'upvote_hint', via: :post
  match '/tag2wronganswers/:tag2wronganswer_id/hints/:id/downvote', to: 'hints#downvote', as: 'downvote_hint', via: :post
  match '/hints/threshold', to: 'hints#edit_threshold', as: "edit_hint_threshold", via: :post
  match '/tag2wronganswers/:tag2wronganswer_id/hints/:id/finalize', to: 'hints#finalize', as: 'finalize_hint', via: :post
  match '/tag2wronganswers/:tag2wronganswer_id/hints/:id/unfinalize', to: 'hints#unfinalize', as: 'unfinalize_hint', via: :post
end

app/models/tag2wronganswer.rb
class Tag2wronganswer < ActiveRecord::Base
    validates :tag, presence: true
    validates :wrong_answer, presence: true
    belongs_to :tag
    belongs_to :wrong_answer
    has_many :hints
    
    def get_finalized_hint
        hints.each do |hint|
            if hint.finalized
                return hint.content
            end
        end
        return false
    end
    
    def self.get_id(wrong_answer, tag)
        tag2wronganswer =  Tag2wronganswer.where(:wrong_answer_id => wrong_answer.id).where(:tag_id => tag.id).first
        if tag2wronganswer
            return tag2wronganswer.id
        end
        # return -1 if error i.e. wrong_answer and tag are not associated
        return -1
    end
    
    def assigned_message
        if self.hints and self.hints.where(:finalized => true)
            return self.hints.where(:finalized => true).first
        else
            return nil
        end
    end
    
    def update_status
        if self.hints.length == 0
           self.update_attribute(:hint_status, "no hints")
        elsif self.hints.where(:finalized => true).exists?
            self.update_attribute(:hint_status, "assigned")
        else
            self.update_attribute(:hint_status, "in progress")
        end
    end
end

app/controllers/tag2wronganswers_controller.rb
class Tag2wronganswersController < ApplicationController
    
    def show
        @tag2wronganswer = Tag2wronganswer.find(params[:id])
        @wrong_answer = @tag2wronganswer.wrong_answer
        @hints = @tag2wronganswer.hints
        if params.has_key?("sort")
            type = params[:sort]
            @hints = sort_messages(type, @hints, true)
        end
        @final_message = @tag2wronganswer.get_finalized_hint || ""
    end
end

app/views/tag2wronganswers/show.html.erb
<h2><%= "Question Set: " + @wrong_answer.question.question_set.name %></h2>
<h4>
    Case String: <%= @wrong_answer.question.case_string %>
</h4>
<h4>
    Question: <%= simple_format(@wrong_answer.question.text) %>
</h4>
<h4>
    Wrong Answer: <%= @wrong_answer.text %>
</h4>
<h4>
    <%= "Status: " + @tag2wronganswer.hint_status + "."%>
    <% if @tag2wronganswer.hint_status == "assigned" %>
      <%= "Message: " + @final_message %>
    <% end %>
</h4>
<h4>
    Tag: <%= @tag2wronganswer.tag.name %>
</h4>

Sort by <%= link_to "Upvotes", tag2wronganswer_path(@tag2wronganswer.id, :sort => "upvotes")%> 
<%= link_to "Downvotes", tag2wronganswer_path(@tag2wronganswer.id, :sort => "downvotes")%>

<div class="row">
  <div class="col-md-8" id="drafts">
    <% @hints.each do |hint| %>
      <br>
      <% if hint.finalizable %>
        <div class="row" id="finalize-<%= hint.id %>">
          <%= link_to "Finalize hint", finalize_hint_path(:tag2wronganswer_id => @tag2wronganswer.id, :id => hint.id), :id => "finalize-#{hint.id}", :method => :post %>
        </div>
      <% end %>
      <% if hint.finalized %>
        <div class="row" id="assigned-hint-<%= hint.id %>">
          Assigned hint
        </div>
      <% end %>
      <div class="row" id="hint-row-<%= hint.id %>">
        <div class="col-md-3" id="votes">
          <div class="row" id="upvotes">
            <div class="col-sm-6" id="upvote-btn-<%= hint.id %>">
              <%= link_to "Upvote", upvote_hint_path(:tag2wronganswer_id => @tag2wronganswer.id, :id => hint.id), :id => "upvote-#{hint.id}", :method => :post, :remote => true %>
            </div>
            <div class="col-sm-6" id="num-upvotes-<%= hint.id %>">
              <%= hint.upvotes %>
            </div>
          </div>
          <div class="row" id="downvotes">
            <div class="col-sm-6" id="downvote-btn-<%= hint.id %>">
              <%= link_to "Downvote", downvote_hint_path(:tag2wronganswer_id => @tag2wronganswer.id, :id => hint.id), id: "downvote-#{hint.id}", :method => :post, :remote => true %>
            </div>
            <div class="col-sm-6" id="num-downvotes-<%= hint.id %>">
              <%= hint.downvotes %>
            </div>
          </div>
        </div>
        <div class="col-md-7" id="hint">
          <%= hint.content %>
        </div>
        <% if not hint.finalized %>
          <div class="col-md-2" id="delete-hint">
            <%= link_to "Delete", tag2wronganswer_hint_path(:tag2wronganswer_id => @tag2wronganswer.id, :id => hint.id), id: "delete-#{hint.id}", :method => :delete, data: { confirm: "Are you sure?" } %>
          </div>
        <% else %>
          <div class="col-md-2" id="unfinalize-hint">
            <%= link_to "Unfinalize", unfinalize_hint_path(:tag2wronganswer_id => @tag2wronganswer.id, :id => hint.id), :id => "unfinalize-#{hint.id}", :method => :post %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="col-md-4" id="compose">
    <div class='Post hint'>
      <%=form_tag(tag2wronganswer_hints_path(:tag2wronganswer_id => @tag2wronganswer.id), :method => :post) do %>
        <%= text_area_tag("add_hint", nil, :placeholder => "New hint", :required => true, :id => "compose-hint-input", :cols => "10") %>
        <br/>
        
        <%= submit_tag("Post hint") %>
      <% end %>
      <% if not @tag2wronganswer.tag.related_hints(@tag2wronganswer).empty? %>
        <%=form_tag(tag2wronganswer_hints_path(:tag2wronganswer_id => @tag2wronganswer.id), :method => :post) do %>  
          <%= select_tag("add_hint", options_for_select(@tag2wronganswer.tag.related_hints(@tag2wronganswer)),  {:include_blank => true}) %>
          
          <%= submit_tag("Use old hint") %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<script>
  $(document).ready(function () {

    $('#add_hint').on('change', function () {
        var myValue = $(this).val();
        $("#compose-hint-input").val(myValue);
    });
  });
</script>