config/routes.rb
Rails.application.routes.draw do
  resources :question_sets do
    resources :questions do
      resources :wrong_answers
    end
  end
  resources :concepts do
    resources :messages
  end
  resources :tag2wronganswers do
    resources :hints
  end
  devise_for :users
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  root to: 'pages#index'
  
  match '/forgot_password', to: 'users#forgot_password', as: "forgot_password", via: :post
  
  match '/display_users', to: 'users#index', via: :get
  match '/display_users', to: 'users#create', via: :post
  match '/display_users', to: 'users#destroy', via: :delete
  match '/display_users/:id', to: 'users#edit', via: :put
  
  match '/upload', to: 'uploads#index', via: :get
  match '/upload', to: 'uploads#new', via: :post
  match '/upload/concepts/confirmation', to: 'upload_concepts#show', via: :get
  match '/upload/concepts/confirmation', to: 'upload_concepts#confirm', via: :put
  match '/upload/tags/confirmation', to: 'upload_tags#show', via: :get
  match '/upload/tags/confirmation', to: 'upload_tags#confirm', via: :put
  match '/upload/tag2concepts/confirmation', to: 'upload_tag2concepts#show', via: :get
  match '/upload/tag2concepts/confirmation', to: 'upload_tag2concepts#confirm', via: :put
  
  match 'upload/questionsets/confirmation', to: 'upload_question_sets#show', via: :get
  match 'upload/questionsets/confirmation', to: 'upload_question_sets#confirm', via: :put
  
  match '/concepts/:concept_id/messages/:id/upvote', to: 'messages#upvote', as: "upvote", via: :post
  match '/concepts/:concept_id/messages/:id/downvote', to: 'messages#downvote', as: "downvote", via: :post
  match '/messages/threshold', to: 'messages#edit_threshold', as: "edit_threshold", via: :post
  match '/concepts/:concept_id/messages/:id/finalize', to: 'messages#finalize', as: 'finalize', via: :post
  match '/concepts/:concept_id/messages/:id/unfinalize', to: 'messages#unfinalize', as: 'unfinalize', via: :post
  
  match '/tag2wronganswers/:tag2wronganswer_id/hints/:id/upvote', to: 'hints#upvote', as: 'upvote_hint', via: :post
  match '/tag2wronganswers/:tag2wronganswer_id/hints/:id/downvote', to: 'hints#downvote', as: 'downvote_hint', via: :post
  match '/hints/threshold', to: 'hints#edit_threshold', as: "edit_hint_threshold", via: :post
  match '/tag2wronganswers/:tag2wronganswer_id/hints/:id/finalize', to: 'hints#finalize', as: 'finalize_hint', via: :post
  match '/tag2wronganswers/:tag2wronganswer_id/hints/:id/unfinalize', to: 'hints#unfinalize', as: 'unfinalize_hint', via: :post
end

app/models/concept.rb
require 'csv'
class Concept < ActiveRecord::Base
    validates :name, presence: true, uniqueness: true
    validates :description, presence: true
    has_many :messages, :dependent => :destroy
    has_many :tag2concepts, :dependent => :destroy
    has_many :tags, :through => :tag2concepts
    include ActiveModel::Serialization
    
    def attributes
        {:name => name, :description => description}    
    end
    
    def get_finalized_message
        messages.each do |message|
            if message.finalized
                return message.content
            end
        end
        return false
    end
    
    def self.verify_row(name, description)
        unless name =~ /\S/
            return "Concept name for one of the concepts is missing. Upload aborted"
        end
        unless description =~ /\S/
            return "Concept description for one of the concepts is missing. Upload aborted"
        else
           return nil 
        end
    end
    def self.verify_first_line(first_line)
        #Check format: concept, description, message
        if first_line.length < 3
          return false
        end
        concept_matches = first_line[0].include?("Concept")
        desc_matches = first_line[1].include?("Description")
        message_matches = first_line[2].include?("Message")
        return concept_matches && desc_matches && message_matches
    end
  
    def self.import(csv_path)
        rows = CSV.read(csv_path)
        if not self.verify_first_line(rows[0])
            return false
        end
        rows.shift

        file_concepts = {}
        rows.each do |row|
            concept_name, description, message = row.map{|n| n.strip if n}
            if not message
                message = ""
            end
            error = verify_row(concept_name, description)
            if error
                return {:error => error}
            end
            file_concepts[concept_name] = [description, message]
        end
    
        return cross_check_diffs(file_concepts)
    end
    
    def self.make_edit(exist_concept, upload_concept)
        #Check if there's an edit. If so, change it but don't save
        #Otherwise return False
        new_description, new_message = upload_concept
        edit = [exist_concept, ""]
        change_discovered = false
        #Check if description changed
        if exist_concept.description != new_description
            exist_concept.description = new_description
            change_discovered = true
        end
        
        #Check if message should be added
        if new_message.length > 0
            if exist_concept.messages.find_by_content(new_message) == nil
                #Message doesn't exist
                edit[1] = new_message
                change_discovered = true
            end
        end
        
        #Serialize the existing_concept
        edit[0] = edit[0].serializable_hash
        
        if change_discovered
            return edit
        else
            return false
        end
    end

    def self.cross_check_diffs(file_concepts)
        #Returns a hash of answers, edits, deletions. Answers and edits contains 
        #a message, which may be an empty string if we do not want to create a new message
        #Note the instances are in json form
        edits = []
        additions = []
        deletions = []

        #First check edits and deletions
        Concept.all.each do |exist_concept|
            if file_concepts.key?(exist_concept.name)
                upload_concept = file_concepts[exist_concept.name]
                any_edits = make_edit(exist_concept, upload_concept)
                if any_edits
                    edits += [any_edits]
                end
            else
                deletions += [exist_concept.serializable_hash]
            end
        end
        
        #Check for any additions
        file_concepts.keys.each do |concept|
            #Check if not in concept not in db
            if not Concept.find_by_name(concept)
                desc, new_message = file_concepts[concept]
                new_concept = Concept.new({:name => concept, :description => desc})
                additions += [[new_concept.serializable_hash, new_message]]
            end
        end
        return {:additions => additions, :deletions => deletions, :edits => edits}
    end
    
    def self.save_changes(changes)
        additions = changes[:additions]
        deletions = changes[:deletions]
        edits = changes[:edits]
        additions.each do |addition, message|
            concept = Concept.create(addition)
            Message.create(:concept_id => concept.id, :content => message)
        end
        
        deletions.each do |deletion|
            Concept.find_by_name(deletion[:name]).destroy
        end
        
        edits.each do |edit, message|
            concept = Concept.find_by_name(edit[:name])
            concept.update(edit)
            Message.create(:concept_id => concept.id, :content => message)
        end
    end
    
    def update_status
        if self.messages.length == 0
           self.update_attribute(:msg_status, "no messages")
        elsif self.messages.where(:finalized => true).exists?
            self.update_attribute(:msg_status, "assigned")
        else
            self.update_attribute(:msg_status, "in progress")
        end
    end
    
    def assigned_message
        if self.messages and self.messages.where(:finalized => true)
            return self.messages.where(:finalized => true).first
        else
            return nil
        end
    end
    
    def display_tags_string
        display_string = ''
        self.tags.each do |tag|
            display_string += tag.name + ", "
        end
        # remove trailing comma
        return display_string[0...-2]
    end
 
end

app/controllers/concepts_controller.rb
class ConceptsController < ApplicationController
    
    def index
        @concepts = Concept.all
        @concepts.each do |concept|
            concept.update_status
        end
        @threshold = Rails.application.config.threshold
    end
    
    def show
        @concept = Concept.find(params[:id])
        @messages = @concept.messages
        if params.has_key?("sort")
            type = params[:sort]
            @messages = sort_messages(type, @messages, false)
        end
        @final_message = @concept.get_finalized_message || ""
    end
    
end

app/views/concepts/index.html.erb
<h1>
    Concepts
</h1>
<% if current_user.admin %>
  <div id="threshold-display">
    <%= "Current threshold: " + @threshold.to_s%>
  </div>
  <%= form_tag(edit_threshold_path, :method => :post) do %>
    <%= text_field_tag("threshold", nil, :placeholder => "Edit threshold", :required => true)%>
    <%= submit_tag("Change") %>
  <% end %>
<% end %>  
<table class="table" id="Concepts">
  <thead>
    <tr>
      <th>Concept</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <% @concepts.each do |concept| %>
      <tr>
        <td><%= link_to concept.name, concept_path(concept.id), :class => "btn"%></td>
        <td><%= concept.msg_status %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/concepts/show.html.erb
<h1>
  <%= @concept.name %>
</h1>
<h3>
  <%= @concept.description %>
</h3>
<h4>
  <%= "Status: " + @concept.msg_status + "."%>
  <% if @concept.msg_status == "assigned" %>
    <%= "Message: " + @final_message %>
  <% end %>
  <%= "Tags: " + @concept.display_tags_string %>
</h4>

Sort by <%= link_to "Upvotes", concept_path(@concept.id, :sort => "upvotes")%> 
<%= link_to "Downvotes", concept_path(@concept.id, :sort => "downvotes")%>
<div class="row">
  <div class="col-md-8" id="drafts">
    <% @messages.each do |message| %>
      <br>
      <% if message.finalizable %>
        <div class="row" id="finalize-<%= message.id %>">
          <%= link_to "Finalize message", finalize_path(:concept_id => @concept.id, :id => message.id), :id => "finalize-#{message.id}", :method => :post %>
        </div>
      <% end %>
      <% if message.finalized %>
        <div class="row" id="assigned-message-<%= message.id %>">
          Assigned message
        </div>
      <% end %>
      <div class="row" id="message-row-<%= message.id %>">
        <div class="col-md-3" id="votes">
          <div class="row" id="upvotes">
            <div class="col-sm-6" id="upvote-btn-<%= message.id %>">
              <%= link_to "Upvote", upvote_path(:concept_id => @concept.id, :id => message.id), :id => "upvote-#{message.id}", :method => :post, :remote => true %>
            </div>
            <div class="col-sm-6" id="num-upvotes-<%= message.id %>">
              <%= message.upvotes %>
            </div>
          </div>
          <div class="row" id="downvotes">
            <div class="col-sm-6" id="downvote-btn-<%= message.id %>">
              <%= link_to "Downvote", downvote_path(:concept_id => @concept.id, :id => message.id), id: "downvote-#{message.id}", :method => :post, :remote => true %>
            </div>
            <div class="col-sm-6" id="num-downvotes-<%= message.id %>">
              <%= message.downvotes %>
            </div>
          </div>
        </div>
        <div class="col-md-7" id="message">
          <%= message.content %>
        </div>
        <% if not message.finalized %>
          <div class="col-md-2" id="delete-message">
            <%= link_to "Delete", concept_message_path(:concept_id => @concept.id, :id => message.id), id: "delete-#{message.id}", :method => :delete, data: { confirm: "Are you sure?" } %>
          </div>
        <% else %>
          <div class="col-md-2" id="unfinalize-message">
            <%= link_to "Unfinalize", unfinalize_path(:concept_id => @concept.id, :id => message.id), :id => "unfinalize-#{message.id}", :method => :post %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="col-md-4" id="compose">
    <div class='Post Message'>
      <%=form_tag(concept_messages_path(:concept_id => @concept.id), :method => :post) do %>
        <%= text_area_tag("add_message", nil, :placeholder => "New Message", :required => true, :id => "compose-message-input", :cols => "10") %>
        <br/>
        <%= submit_tag("Post Message") %>
      <% end %>
    </div>
  </div>
</div>