config/routes.rb
Rails.application.routes.draw do
  resources :question_sets do
    resources :questions do
      resources :wrong_answers
    end
  end
  resources :concepts do
    resources :messages
  end
  resources :tag2wronganswers do
    resources :hints
  end
  devise_for :users
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  root to: 'pages#index'
  
  match '/forgot_password', to: 'users#forgot_password', as: "forgot_password", via: :post
  
  match '/display_users', to: 'users#index', via: :get
  match '/display_users', to: 'users#create', via: :post
  match '/display_users', to: 'users#destroy', via: :delete
  match '/display_users/:id', to: 'users#edit', via: :put
  
  match '/upload', to: 'uploads#index', via: :get
  match '/upload', to: 'uploads#new', via: :post
  match '/upload/concepts/confirmation', to: 'upload_concepts#show', via: :get
  match '/upload/concepts/confirmation', to: 'upload_concepts#confirm', via: :put
  match '/upload/tags/confirmation', to: 'upload_tags#show', via: :get
  match '/upload/tags/confirmation', to: 'upload_tags#confirm', via: :put
  match '/upload/tag2concepts/confirmation', to: 'upload_tag2concepts#show', via: :get
  match '/upload/tag2concepts/confirmation', to: 'upload_tag2concepts#confirm', via: :put
  
  match 'upload/questionsets/confirmation', to: 'upload_question_sets#show', via: :get
  match 'upload/questionsets/confirmation', to: 'upload_question_sets#confirm', via: :put
  
  match '/concepts/:concept_id/messages/:id/upvote', to: 'messages#upvote', as: "upvote", via: :post
  match '/concepts/:concept_id/messages/:id/downvote', to: 'messages#downvote', as: "downvote", via: :post
  match '/messages/threshold', to: 'messages#edit_threshold', as: "edit_threshold", via: :post
  match '/concepts/:concept_id/messages/:id/finalize', to: 'messages#finalize', as: 'finalize', via: :post
  match '/concepts/:concept_id/messages/:id/unfinalize', to: 'messages#unfinalize', as: 'unfinalize', via: :post
  
  match '/tag2wronganswers/:tag2wronganswer_id/hints/:id/upvote', to: 'hints#upvote', as: 'upvote_hint', via: :post
  match '/tag2wronganswers/:tag2wronganswer_id/hints/:id/downvote', to: 'hints#downvote', as: 'downvote_hint', via: :post
  match '/hints/threshold', to: 'hints#edit_threshold', as: "edit_hint_threshold", via: :post
  match '/tag2wronganswers/:tag2wronganswer_id/hints/:id/finalize', to: 'hints#finalize', as: 'finalize_hint', via: :post
  match '/tag2wronganswers/:tag2wronganswer_id/hints/:id/unfinalize', to: 'hints#unfinalize', as: 'unfinalize_hint', via: :post
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
    
    def new
        #Based on file being uploaded, redirect to its upload controller
        if not params.has_key?("file")
            flash[:notice] = "Please attach a file"
            render :index and return
        end
        file_type = params[:file_type].split()[0].downcase #(ie Concepts, Tags)
        
        #No confirmation on Users
        if file_type == "users"
            flash[:notice] = User.import(current_user, File.open(params[:file].tempfile))
            render :index
        else
            redirect_to(controller: "upload_" + file_type, action: :show, path: params[:file].path)
        end
    end
end

app/views/uploads/index.html.erb
<h3>Upload a File</h3>
  <%= form_tag upload_path, multipart: true do %>
    <div class="form-group">
      <label for="sel1">Select list:</label>
      <select class="form-control" id="sel1" name="file_type">
        <option>Users (csv)</option>
        <option>Concepts (csv)</option>
        <option>Tags (csv)</option>
        <option>Tag2concepts (csv)</option>
        <option>Question_Sets (json)</option>
      </select>
    </div>
    <%= file_field_tag :file %>
    <%= submit_tag "Upload" %>
  <% end %>

app/views/uploads/new.html.erb
<h1>Confirmation Page</h1>
<div class="form-group">
  <%=form_tag(upload_confirmation_path, :method => :put, :id => "confirm_form") do %>
    <table class="table" id="Additions">
      <h3>Additions</h3>
      <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Message</th>
            <th>Confirm</th>
        </tr>
      </thead>
      <tbody>
        <% @additions.each do |addition, message| %>
          <tr>
            <td>
              <%= addition[:name]  %>
            </td>
            <td>
              <%= addition[:description] %>
            </td>
            <td>
              <%= message %>
            </td>
            <td>
              <%= check_box_tag("confirmed_additions[]", [addition, message].to_s, false, 
                    :id => "add_" + addition[:name]) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <table class="table" id="Deletions">
      <h3>Deletions</h3>
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Confirm</th>
        </tr>
      </thead>
      <tbody>
        <% @deletions.each do |deletion| %>
          <tr>
            <td>
              <%= deletion[:name] %>
            </td>
            <td>
              <%= deletion[:description] %>
            </td>
            <td>
              <%= check_box_tag("confirmed_deletions[]", deletion.to_s, false, 
                    :id => "delete_" + deletion[:name]) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    
    <table class="table" id="Edits">
      <h3>Edit</h3>
      <thead>
        <tr>
          <th>Name</th>
          <th>Old Description</th>
          <th>New Description</th>
          <th>Added Message</th>
          <th>Confirm</th>
        </tr>
      </thead>
      <tbody>
        <% @edits.each do |edit, message| %>
          <tr>
            <td>
              <%= edit[:name] %>
            </td>
            <td>
                <%= Concept.find_by_name(edit[:name]).description %>
            </td>
            <td>
              <%= edit[:description] %>
            </td>
            <td>
              <%= message %>
            </td>
            <td>
              <%= check_box_tag("confirmed_edits[]", [edit, message].to_s, false, 
                    :id => "edits_" + edit[:name]) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
      <%= submit_tag "Confirm Upload" %>
  <% end %>
</div>