config/routes.rb
Rails.application.routes.draw do
  resources :question_sets do
    resources :questions do
      resources :wrong_answers
    end
  end
  resources :concepts do
    resources :messages
  end
  resources :tag2wronganswers do
    resources :hints
  end
  devise_for :users
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  root to: 'pages#index'
  
  match '/forgot_password', to: 'users#forgot_password', as: "forgot_password", via: :post
  
  match '/display_users', to: 'users#index', via: :get
  match '/display_users', to: 'users#create', via: :post
  match '/display_users', to: 'users#destroy', via: :delete
  match '/display_users/:id', to: 'users#edit', via: :put
  
  match '/upload', to: 'uploads#index', via: :get
  match '/upload', to: 'uploads#new', via: :post
  match '/upload/concepts/confirmation', to: 'upload_concepts#show', via: :get
  match '/upload/concepts/confirmation', to: 'upload_concepts#confirm', via: :put
  match '/upload/tags/confirmation', to: 'upload_tags#show', via: :get
  match '/upload/tags/confirmation', to: 'upload_tags#confirm', via: :put
  match '/upload/tag2concepts/confirmation', to: 'upload_tag2concepts#show', via: :get
  match '/upload/tag2concepts/confirmation', to: 'upload_tag2concepts#confirm', via: :put
  
  match 'upload/questionsets/confirmation', to: 'upload_question_sets#show', via: :get
  match 'upload/questionsets/confirmation', to: 'upload_question_sets#confirm', via: :put
  
  match '/concepts/:concept_id/messages/:id/upvote', to: 'messages#upvote', as: "upvote", via: :post
  match '/concepts/:concept_id/messages/:id/downvote', to: 'messages#downvote', as: "downvote", via: :post
  match '/messages/threshold', to: 'messages#edit_threshold', as: "edit_threshold", via: :post
  match '/concepts/:concept_id/messages/:id/finalize', to: 'messages#finalize', as: 'finalize', via: :post
  match '/concepts/:concept_id/messages/:id/unfinalize', to: 'messages#unfinalize', as: 'unfinalize', via: :post
  
  match '/tag2wronganswers/:tag2wronganswer_id/hints/:id/upvote', to: 'hints#upvote', as: 'upvote_hint', via: :post
  match '/tag2wronganswers/:tag2wronganswer_id/hints/:id/downvote', to: 'hints#downvote', as: 'downvote_hint', via: :post
  match '/hints/threshold', to: 'hints#edit_threshold', as: "edit_hint_threshold", via: :post
  match '/tag2wronganswers/:tag2wronganswer_id/hints/:id/finalize', to: 'hints#finalize', as: 'finalize_hint', via: :post
  match '/tag2wronganswers/:tag2wronganswer_id/hints/:id/unfinalize', to: 'hints#unfinalize', as: 'unfinalize_hint', via: :post
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cs61aHintr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <%= link_to 'hintr', root_path, class: 'navbar-brand' %>
      </div>
      <div id="navbar">
       <ul class="nav navbar-nav pull-right">
          <% if user_signed_in? %>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <%= current_user.name %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu" id="menu">
                <li><%= link_to 'Profile', edit_user_registration_path %></li>
                <li><%= link_to 'Log out', destroy_user_session_path, method: :delete, :id => "Logout"%></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Log In', new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>
  </div>

    <%= yield :top_content %>

  <div class="container">
    <div class="row">
      <% if user_signed_in? %>
        <div class="col-sm-2">
          <ul class="nav nav-pills nav-stacked">
            <li role="presentation"><%= link_to 'Home', root_path %></li>
            <li role="presentation"><%= link_to 'Users', display_users_path %></li>
            <li role="presentation"><%= link_to 'Uploads', upload_path %></li>
            <li role="presentation"><%= link_to 'Concepts', concepts_path %></li>
            <li role="presentation"><%= link_to 'Question Sets', question_sets_path %></li>
          </ul>
        </div>
        <div class="col-sm-10">
          <h1><%= yield :header %></h1>
          <%= yield %>
        </div>
      <% else %>
        <h1><%= yield :header %></h1>
        <%= yield %>
      <% end %>
    </div>
  </div>

</body>
</html>